
test:
  description: ""
  fields:
    entity_id:
      description: Identifier of the Max! entity.
      example: ""

remove:
  description: Remove a Max! entity
  fields:
    entity_id:
      description: Identifier of the Max! entity.
      example: ""

add:
  description: Add a Max! entitity
  fields:
    actions:
      description: ""
      example: ""

edit:
  description: Edit a Max! entitity
  fields:
    entity_id:
      description: Identifier of the Max! entity.
      example: ""
    actions:
      description:""
      example: ""
